#!/usr/bin/ruby -w

require 'ostruct'

list = []

list << OpenStruct(Hash[:product_id,3,:photo_url,"http://www.hydrogarden.com/StockPics/01-005-015_GH_aquafarm.JPG"])
list << OpenStruct(Hash[:product_id,5,:photo_url,"http://www.hydrogarden.com/StockPics/01-005-200_GH_AquafarmKit_Only.JPG"])
list << OpenStruct(Hash[:product_id,6,:photo_url,"http://www.hydrogarden.com/StockPics/01-005-205_GH_WaterfarmKit_Only.JPG"])
list << OpenStruct(Hash[:product_id,7,:photo_url,"http://www.hydrogarden.com/StockPics/Hallida_AirPump_8outlet.jpg"])
list << OpenStruct(Hash[:product_id,8,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot46mm.jpg"])
list << OpenStruct(Hash[:product_id,9,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot51mm.jpg"])
list << OpenStruct(Hash[:product_id,10,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot77mm.jpg"])
list << OpenStruct(Hash[:product_id,12,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot_HeavyDuty_80mm.jpg"])
list << OpenStruct(Hash[:product_id,13,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot_HeavyDuty_140mm.jpg"])
list << OpenStruct(Hash[:product_id,14,:photo_url,"http://www.hydrogarden.com/StockPics/Netpot_HeavyDuty_200mm.jpg"])
list << OpenStruct(Hash[:product_id,25,:photo_url,"http://www.hydrogarden.com/StockPics/01-005-040_GH_rainforest_motor.JPG"])
list << OpenStruct(Hash[:product_id,26,:photo_url,"http://www.hydrogarden.com/StockPics/Square_pot10cm.jpg"])
list << OpenStruct(Hash[:product_id,27,:photo_url,"http://www.hydrogarden.com/StockPics/Square_pot13cm.jpg"])
list << OpenStruct(Hash[:product_id,28,:photo_url,"http://www.hydrogarden.com/StockPics/Square_pot15cm.jpg"])
list << OpenStruct(Hash[:product_id,33,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,34,:photo_url,"http://www.hydrogarden.com/StockPics/01-010-015_15L_pot.JPG"])
list << OpenStruct(Hash[:product_id,35,:photo_url,"http://www.hydrogarden.com/StockPics/01-010-015_15L_Saucer.JPG"])
list << OpenStruct(Hash[:product_id,37,:photo_url,"http://www.hydrogarden.com/StockPics/01-010-080_20L_Pot.JPG"])
list << OpenStruct(Hash[:product_id,38,:photo_url,"http://www.hydrogarden.com/StockPics/01-010-090_30L_Pot.jpg"])
list << OpenStruct(Hash[:product_id,63,:photo_url,"http://www.hydrogarden.com/StockPics/Dualflow_system.JPG"])
list << OpenStruct(Hash[:product_id,64,:photo_url,"http://www.hydrogarden.com/StockPics/Dualflow_tank80L.JPG"])
list << OpenStruct(Hash[:product_id,65,:photo_url,"http://www.hydrogarden.com/StockPics/Dualflow_tray.JPG"])
list << OpenStruct(Hash[:product_id,66,:photo_url,"http://www.hydrogarden.com/StockPics/Dualflow_Correxcover.JPG"])
list << OpenStruct(Hash[:product_id,92,:photo_url,"http://www.hydrogarden.com/StockPics/Accent3x3_FloodDrain_Tray.JPG"])
list << OpenStruct(Hash[:product_id,93,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrogarden_3x3FloodDrainKitJPG.JPG"])
list << OpenStruct(Hash[:product_id,113,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_TubOutlet.JPG"])
list << OpenStruct(Hash[:product_id,114,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_TubOutlet.JPG"])
list << OpenStruct(Hash[:product_id,115,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_25mm_TubOutlet.JPG"])
list << OpenStruct(Hash[:product_id,116,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_35mm_OutletExtension.JPG"])
list << OpenStruct(Hash[:product_id,117,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_TubOutletScreen.JPG"])
list << OpenStruct(Hash[:product_id,118,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_7mmFlexiTube.jpg"])
list << OpenStruct(Hash[:product_id,119,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_BarbCross.JPG"])
list << OpenStruct(Hash[:product_id,120,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_BarbElbow.JPG"])
list << OpenStruct(Hash[:product_id,121,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_BarbJoiner.JPG"])
list << OpenStruct(Hash[:product_id,122,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_BarbTee.JPG"])
list << OpenStruct(Hash[:product_id,123,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_GoofRepairPlug.JPG"])
list << OpenStruct(Hash[:product_id,124,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_InlineValve.JPG"])
list << OpenStruct(Hash[:product_id,125,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_SaddleClamp.JPG"])
list << OpenStruct(Hash[:product_id,126,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_BarbElbow.jpg"])
list << OpenStruct(Hash[:product_id,127,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_BarbEndPlug.JPG"])
list << OpenStruct(Hash[:product_id,128,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_BarbInlineJoiner.JPG"])
list << OpenStruct(Hash[:product_id,129,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mmBarb_13mmTakeOff.jpg"])
list << OpenStruct(Hash[:product_id,130,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_BarbTee.JPG"])
list << OpenStruct(Hash[:product_id,131,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_TopHatGrommet.JPG"])
list << OpenStruct(Hash[:product_id,132,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_InlineFilterBlack.jpg"])
list << OpenStruct(Hash[:product_id,133,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_InlineValve.JPG"])
list << OpenStruct(Hash[:product_id,134,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_NutandTail.jpg"])
list << OpenStruct(Hash[:product_id,135,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_PipeClampSaddle.JPG"])
list << OpenStruct(Hash[:product_id,136,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_PipeRatchetClip.jpg"])
list << OpenStruct(Hash[:product_id,137,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_13mm_PolyToHoseConnector.jpg"])
list << OpenStruct(Hash[:product_id,138,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_BarbElbow.jpg"])
list << OpenStruct(Hash[:product_id,139,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_BarbEndPlug.jpg"])
list << OpenStruct(Hash[:product_id,140,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_BarbJoiner.JPG"])
list << OpenStruct(Hash[:product_id,141,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_BarbTee.JPG"])
list << OpenStruct(Hash[:product_id,142,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_CurvedGrommet.JPG"])
list << OpenStruct(Hash[:product_id,143,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,144,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,145,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_InlineValve.JPG"])
list << OpenStruct(Hash[:product_id,146,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_LDPE_LowDensityPipe.JPG"])
list << OpenStruct(Hash[:product_id,147,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_NutandTail.jpg"])
list << OpenStruct(Hash[:product_id,148,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_PipeClampSaddle.JPG"])
list << OpenStruct(Hash[:product_id,149,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_FlexiblePipe.JPG"])
list << OpenStruct(Hash[:product_id,150,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_PipeRatchetClip.jpg"])
list << OpenStruct(Hash[:product_id,151,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_13mmReducerJoiner.JPG"])
list << OpenStruct(Hash[:product_id,152,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_19mm_13mmReducerTee.jpg"])
list << OpenStruct(Hash[:product_id,153,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_PunchSpanner.JPG"])
list << OpenStruct(Hash[:product_id,154,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_AdjustableDripper_OnStake.JPG"])
list << OpenStruct(Hash[:product_id,155,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_4mm_AdjustableDripper.JPG"])
list << OpenStruct(Hash[:product_id,156,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_AgriDripper_2lph.JPG"])
list << OpenStruct(Hash[:product_id,157,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_RedBase180.jpg"])
list << OpenStruct(Hash[:product_id,158,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_RedBase360.jpg"])
list << OpenStruct(Hash[:product_id,159,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_RedBase2x20.jpg"])
list << OpenStruct(Hash[:product_id,160,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_RedBase90.jpg"])
list << OpenStruct(Hash[:product_id,161,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_BlueBase180.jpg"])
list << OpenStruct(Hash[:product_id,162,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_BlueBase360.jpg"])
list << OpenStruct(Hash[:product_id,163,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_BlueBase2x20.jpg"])
list << OpenStruct(Hash[:product_id,164,:photo_url,"http://www.hydrogarden.com/StockPics/PPI_MicroSpray_BlueBase90.jpg"])
list << OpenStruct(Hash[:product_id,214,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrogarden_1mPolarGullyKit.JPG"])
list << OpenStruct(Hash[:product_id,215,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrogarden_1mHydroGullyKit.JPG"])
list << OpenStruct(Hash[:product_id,220,:photo_url,"http://www.hydrogarden.com/StockPics/Ceramic_airstone40cm.JPG"])
list << OpenStruct(Hash[:product_id,221,:photo_url,"http://www.hydrogarden.com/StockPics/Ceramic_airstone60cm.JPG"])
list << OpenStruct(Hash[:product_id,223,:photo_url,"http://www.hydrogarden.com/StockPics/Ceramic_AirstoneRound.JPG"])
list << OpenStruct(Hash[:product_id,224,:photo_url,"http://www.hydrogarden.com/StockPics/Ceramic_AirstoneRound.JPG"])
list << OpenStruct(Hash[:product_id,225,:photo_url,"http://www.hydrogarden.com/StockPics/Ceramic_AirstoneRound.JPG"])
list << OpenStruct(Hash[:product_id,226,:photo_url,"http://www.hydrogarden.com/StockPics/Flexible_rubber_airstone.jpg"])
list << OpenStruct(Hash[:product_id,227,:photo_url,"http://www.hydrogarden.com/StockPics/Flexible_rubber_airstone.jpg"])
list << OpenStruct(Hash[:product_id,229,:photo_url,"http://www.hydrogarden.com/StockPics/10-460-120_AirlineSilicon.jpg"])
list << OpenStruct(Hash[:product_id,230,:photo_url,"http://www.hydrogarden.com/StockPics/Aquarline_6outlet_Divider.jpg"])
list << OpenStruct(Hash[:product_id,231,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,387,:photo_url,"http://www.hydrogarden.com/StockPics/spreader_matt.jpg"])
list << OpenStruct(Hash[:product_id,394,:photo_url,"http://www.hydrogarden.com/StockPics/Vermiculite_100L.jpg"])
list << OpenStruct(Hash[:product_id,399,:photo_url,"http://www.hydrogarden.com/StockPics/Heatshield.JPG"])
list << OpenStruct(Hash[:product_id,400,:photo_url,"http://www.hydrogarden.com/StockPics/JackChain.JPG"])
list << OpenStruct(Hash[:product_id,407,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkGrow_SW1L.jpg"])
list << OpenStruct(Hash[:product_id,408,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkGrow_SW5L.jpg"])
list << OpenStruct(Hash[:product_id,410,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkGrow_SW20L.jpg"])
list << OpenStruct(Hash[:product_id,411,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkBloom_SW1L.jpg"])
list << OpenStruct(Hash[:product_id,412,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkBloom_SW5L.jpg"])
list << OpenStruct(Hash[:product_id,414,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,415,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkGrow_HW1L.jpg"])
list << OpenStruct(Hash[:product_id,416,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkGrow_HW5L.jpg"])
list << OpenStruct(Hash[:product_id,418,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,419,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkBloom_HW1L.jpg"])
list << OpenStruct(Hash[:product_id,420,:photo_url,"http://www.hydrogarden.com/StockPics/VitalinkBloom_HW5L.jpg"])
list << OpenStruct(Hash[:product_id,422,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,445,:photo_url,"http://www.hydrogarden.com/StockPics/VitaLink_BioPlus_250ml.jpg"])
list << OpenStruct(Hash[:product_id,450,:photo_url,"http://www.hydrogarden.com/StockPics/VitaLink_buddy1L.jpg"])
list << OpenStruct(Hash[:product_id,451,:photo_url,"http://www.hydrogarden.com/StockPics/VitaLink_buddy5L.jpg"])
list << OpenStruct(Hash[:product_id,453,:photo_url,"http://www.hydrogarden.com/StockPics/Vitalink_FoliarFeed.JPG"])
list << OpenStruct(Hash[:product_id,458,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive0.5oz.jpg"])
list << OpenStruct(Hash[:product_id,459,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive1oz.jpg"])
list << OpenStruct(Hash[:product_id,460,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive2oz.jpg"])
list << OpenStruct(Hash[:product_id,461,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive4oz.jpg"])
list << OpenStruct(Hash[:product_id,462,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive1pint.jpg"])
list << OpenStruct(Hash[:product_id,463,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,464,:photo_url,"http://www.hydrogarden.com/StockPics/superthrive_Gallon.jpg"])
list << OpenStruct(Hash[:product_id,465,:photo_url,"http://www.hydrogarden.com/StockPics/Carbonfilter_160.JPG"])
list << OpenStruct(Hash[:product_id,466,:photo_url,"http://www.hydrogarden.com/StockPics/09-420-055_pHDown_250ml.JPG"])
list << OpenStruct(Hash[:product_id,467,:photo_url,"http://www.hydrogarden.com/StockPics/09-420-060_pHDown_1L.JPG"])
list << OpenStruct(Hash[:product_id,468,:photo_url,"http://www.hydrogarden.com/StockPics/09-420-065_pHDown_5L.JPG"])
list << OpenStruct(Hash[:product_id,469,:photo_url,"http://www.hydrogarden.com/StockPics/09-420-070_pHUp_250ml.JPG"])
list << OpenStruct(Hash[:product_id,471,:photo_url,"http://www.hydrogarden.com/StockPics/clay.jpg"])
list << OpenStruct(Hash[:product_id,472,:photo_url,"http://www.hydrogarden.com/StockPics/clay_pebbles10L.JPG"])
list << OpenStruct(Hash[:product_id,473,:photo_url,"http://www.hydrogarden.com/StockPics/clay_pebbles50L.JPG"])
list << OpenStruct(Hash[:product_id,474,:photo_url,"http://www.hydrogarden.com/StockPics/clay_pebbles50L.JPG"])
list << OpenStruct(Hash[:product_id,479,:photo_url,"http://www.hydrogarden.com/StockPics/Cannacoco_peat50L.JPG"])
list << OpenStruct(Hash[:product_id,480,:photo_url,"http://www.hydrogarden.com/StockPics/02-055-025_BioBizz_CocoMix50L.jpg"])
list << OpenStruct(Hash[:product_id,484,:photo_url,"http://www.hydrogarden.com/StockPics/Grodan_ExpertSlab.JPG"])
list << OpenStruct(Hash[:product_id,492,:photo_url,"http://www.hydrogarden.com/StockPics/Grodan_SBScube.JPG"])
list << OpenStruct(Hash[:product_id,493,:photo_url,"http://www.hydrogarden.com/StockPics/Grodan_SBScube.JPG"])
list << OpenStruct(Hash[:product_id,497,:photo_url,"http://www.hydrogarden.com/StockPics/Grodan_Hugo.JPG"])
list << OpenStruct(Hash[:product_id,498,:photo_url,"http://www.hydrogarden.com/StockPics/Perlite_100L.jpg"])
list << OpenStruct(Hash[:product_id,500,:photo_url,"http://www.hydrogarden.com/StockPics/02-075-040_Canna_TerraSeedMix.jpg"])
list << OpenStruct(Hash[:product_id,501,:photo_url,"http://www.hydrogarden.com/StockPics/CannaProfessional_SoilMix.jpg"])
list << OpenStruct(Hash[:product_id,502,:photo_url,"http://www.hydrogarden.com/StockPics/02-075-075_Canna_ProfessionalSoil.jpg"])
list << OpenStruct(Hash[:product_id,503,:photo_url,"http://www.hydrogarden.com/StockPics/02-075-100_BioBizz_LightMix_Soil50L.jpg"])
list << OpenStruct(Hash[:product_id,504,:photo_url,"http://www.hydrogarden.com/StockPics/02-075-110_BioBizz_AllMixSoil50L.jpg"])
list << OpenStruct(Hash[:product_id,505,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,506,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,507,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,508,:photo_url,"http://www.hydrogarden.com/StockPics/Jiffy7_LoosePlugs.jpg"])
list << OpenStruct(Hash[:product_id,509,:photo_url,"http://www.hydrogarden.com/StockPics/FlexiMix_72BPlugs.jpg"])
list << OpenStruct(Hash[:product_id,511,:photo_url,"http://www.hydrogarden.com/StockPics/12-550-090_Fleximix_Courier5.jpg"])
list << OpenStruct(Hash[:product_id,512,:photo_url,"http://www.hydrogarden.com/StockPics/05-225-015_BioBizz_WormHumus40L.jpg"])
list << OpenStruct(Hash[:product_id,535,:photo_url,"http://www.hydrogarden.com/StockPics/PowerPlant_Ballast.jpg"])
list << OpenStruct(Hash[:product_id,536,:photo_url,"http://www.hydrogarden.com/StockPics/PowerPlant_Ballast.jpg"])
list << OpenStruct(Hash[:product_id,537,:photo_url,"http://www.hydrogarden.com/StockPics/PowerPlant_Ballast.jpg"])
list << OpenStruct(Hash[:product_id,538,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,539,:photo_url,"http://www.hydrogarden.com/StockPics/AvengerAdjustawing_ReflectorLarge.JPG"])
list << OpenStruct(Hash[:product_id,540,:photo_url,"http://www.hydrogarden.com/StockPics/250w_Philips_sonT.jpg"])
list << OpenStruct(Hash[:product_id,541,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,542,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,544,:photo_url,"http://www.hydrogarden.com/StockPics/600w_osramNavT.jpg"])
list << OpenStruct(Hash[:product_id,545,:photo_url,"http://www.hydrogarden.com/StockPics/400w_osram_plantastar.jpg"])
list << OpenStruct(Hash[:product_id,546,:photo_url,"http://www.hydrogarden.com/StockPics/Philips_sonT.jpg"])
list << OpenStruct(Hash[:product_id,547,:photo_url,"http://www.hydrogarden.com/StockPics/Philips_sonT_agro.jpg"])
list << OpenStruct(Hash[:product_id,548,:photo_url,"http://www.hydrogarden.com/StockPics/PhilipsHPIT_lamp.jpg"])
list << OpenStruct(Hash[:product_id,549,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,550,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,552,:photo_url,"http://www.hydrogarden.com/StockPics/600w_osramNavT.jpg"])
list << OpenStruct(Hash[:product_id,553,:photo_url,"http://www.hydrogarden.com/StockPics/600w_osram_plantastar.jpg"])
list << OpenStruct(Hash[:product_id,554,:photo_url,"http://www.hydrogarden.com/StockPics/Philips_sonT.jpg"])
list << OpenStruct(Hash[:product_id,555,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,557,:photo_url,"http://www.hydrogarden.com/StockPics/600w_osramNavT.jpg"])
list << OpenStruct(Hash[:product_id,558,:photo_url,"http://www.hydrogarden.com/StockPics/1000w_sonT.jpg"])
list << OpenStruct(Hash[:product_id,559,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,560,:photo_url,"http://www.hydrogarden.com/StockPics/1000w_PhilipsHPIT.jpg"])
list << OpenStruct(Hash[:product_id,561,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,562,:photo_url,"http://www.hydrogarden.com/StockPics/03-125-050_PPLightsafe_ContactorRelay_2gang.jpg"])
list << OpenStruct(Hash[:product_id,563,:photo_url,"http://www.hydrogarden.com/StockPics/03-125-055_PPLightsafe_ContactorRelay_4gang.jpg"])
list << OpenStruct(Hash[:product_id,564,:photo_url,"http://www.hydrogarden.com/StockPics/03-125-150_PPLightsafe_ContactorTimer_4gang.jpg"])
list << OpenStruct(Hash[:product_id,565,:photo_url,"http://www.hydrogarden.com/StockPics/03-125-155_PPLightsafe_ContactorTimer_6gang.jpg"])
list << OpenStruct(Hash[:product_id,568,:photo_url,"http://www.hydrogarden.com/StockPics/Lightrail3.5_smartdrive.JPG"])
list << OpenStruct(Hash[:product_id,569,:photo_url,"http://www.hydrogarden.com/StockPics/lightrail3.5_TrolleyWheel.JPG"])
list << OpenStruct(Hash[:product_id,570,:photo_url,"http://www.hydrogarden.com/StockPics/lightrail3.5_DriveWheel.JPG"])
list << OpenStruct(Hash[:product_id,571,:photo_url,"http://www.hydrogarden.com/StockPics/55w_philips_cool.jpg"])
list << OpenStruct(Hash[:product_id,572,:photo_url,"http://www.hydrogarden.com/StockPics/03_115_015_150w_cfl_cool_lamp.jpg"])
list << OpenStruct(Hash[:product_id,573,:photo_url,"http://www.hydrogarden.com/StockPics/03_115_017_150w_cfl_warm_lamp.jpg"])
list << OpenStruct(Hash[:product_id,574,:photo_url,"http://www.hydrogarden.com/StockPics/03_115_020_250w_cfl_cool_lamp.jpg"])
list << OpenStruct(Hash[:product_id,576,:photo_url,"http://www.hydrogarden.com/StockPics/03_115_022_250w_cfl_warm_lamp.jpg"])
list << OpenStruct(Hash[:product_id,577,:photo_url,"http://www.hydrogarden.com/StockPics/Heatshield.JPG"])
list << OpenStruct(Hash[:product_id,586,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_HW1L.JPG"])
list << OpenStruct(Hash[:product_id,587,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_SW1L.JPG"])
list << OpenStruct(Hash[:product_id,588,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_HW5L.JPG"])
list << OpenStruct(Hash[:product_id,589,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_SW5L.JPG"])
list << OpenStruct(Hash[:product_id,590,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_HW10L.JPG"])
list << OpenStruct(Hash[:product_id,591,:photo_url,"http://www.hydrogarden.com/StockPics/canna_vegaA&B_SW10L.JPG"])
list << OpenStruct(Hash[:product_id,592,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_HW1L.JPG"])
list << OpenStruct(Hash[:product_id,593,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_SW1L.JPG"])
list << OpenStruct(Hash[:product_id,594,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_HW5L.JPG"])
list << OpenStruct(Hash[:product_id,595,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_SW5L.JPG"])
list << OpenStruct(Hash[:product_id,596,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_HW10L.JPG"])
list << OpenStruct(Hash[:product_id,597,:photo_url,"http://www.hydrogarden.com/StockPics/canna_floresA&B_SW10L.JPG"])
list << OpenStruct(Hash[:product_id,598,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_cocoA&B1L.JPG"])
list << OpenStruct(Hash[:product_id,599,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_cocoA&B5L.JPG"])
list << OpenStruct(Hash[:product_id,600,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_cocoA&B10L.JPG"])
list << OpenStruct(Hash[:product_id,601,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraVega1L.jpg"])
list << OpenStruct(Hash[:product_id,602,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraVega5L.jpg"])
list << OpenStruct(Hash[:product_id,603,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraVega10L.jpg"])
list << OpenStruct(Hash[:product_id,604,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraFlores1L.jpg"])
list << OpenStruct(Hash[:product_id,605,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraFlores5L.jpg"])
list << OpenStruct(Hash[:product_id,606,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_TerraFlores10L.jpg"])
list << OpenStruct(Hash[:product_id,607,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_Ca.jpg"])
list << OpenStruct(Hash[:product_id,608,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_fe.jpg"])
list << OpenStruct(Hash[:product_id,609,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_additive_Mg0.jpg"])
list << OpenStruct(Hash[:product_id,610,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_N.JPG"])
list << OpenStruct(Hash[:product_id,611,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_P.JPG"])
list << OpenStruct(Hash[:product_id,612,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_K.JPG"])
list << OpenStruct(Hash[:product_id,613,:photo_url,"http://www.hydrogarden.com/StockPics/canna_additive_Tracemix.jpg"])
list << OpenStruct(Hash[:product_id,614,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaVega_A&B1L.jpg"])
list << OpenStruct(Hash[:product_id,615,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaVega_A&B5L.jpg"])
list << OpenStruct(Hash[:product_id,616,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaVega_A&B10L.jpg"])
list << OpenStruct(Hash[:product_id,617,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaFlores_A&B1L.jpg"])
list << OpenStruct(Hash[:product_id,618,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaFlores_A&B5L.jpg"])
list << OpenStruct(Hash[:product_id,619,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_AquaFlores_A&B10L.jpg"])
list << OpenStruct(Hash[:product_id,620,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-305_Canna_BioVega1L.jpg"])
list << OpenStruct(Hash[:product_id,621,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-310_Canna_BioVega5L.jpg"])
list << OpenStruct(Hash[:product_id,622,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-315_Canna_BioFlores1L.jpg"])
list << OpenStruct(Hash[:product_id,623,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-320_Canna_BioFlores5L.jpg"])
list << OpenStruct(Hash[:product_id,624,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-325_Canna_BioBoost1L.jpg"])
list << OpenStruct(Hash[:product_id,625,:photo_url,"http://www.hydrogarden.com/StockPics/05-205-330_Canna_BioBoost25ml.jpg"])
list << OpenStruct(Hash[:product_id,629,:photo_url,"http://www.hydrogarden.com/StockPics/canna_rhizotonic250ml.jpg"])
list << OpenStruct(Hash[:product_id,630,:photo_url,"http://www.hydrogarden.com/StockPics/canna_rhizotonic1L.jpg"])
list << OpenStruct(Hash[:product_id,631,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,633,:photo_url,"http://www.hydrogarden.com/StockPics/cannazym_1L.JPG"])
list << OpenStruct(Hash[:product_id,634,:photo_url,"http://www.hydrogarden.com/StockPics/cannazym_5L.JPG"])
list << OpenStruct(Hash[:product_id,636,:photo_url,"http://www.hydrogarden.com/StockPics/cannaPK13_14_1L.JPG"])
list << OpenStruct(Hash[:product_id,637,:photo_url,"http://www.hydrogarden.com/StockPics/cannaPK13_14_5L.JPG"])
list << OpenStruct(Hash[:product_id,638,:photo_url,"http://www.hydrogarden.com/StockPics/canna_trichoderma.jpg"])
list << OpenStruct(Hash[:product_id,640,:photo_url,"http://www.hydrogarden.com/StockPics/06-255-100_canna_Boost_Accelerator_250ml.jpg"])
list << OpenStruct(Hash[:product_id,641,:photo_url,"http://www.hydrogarden.com/StockPics/06-255-110_canna_Boost_Accelerator_1L.jpg"])
list << OpenStruct(Hash[:product_id,642,:photo_url,"http://www.hydrogarden.com/StockPics/06-255-120_canna_Boost_Accelerator_5L.jpg"])
list << OpenStruct(Hash[:product_id,648,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,649,:photo_url,"http://www.hydrogarden.com/StockPics/05-225-025_BioBizz_BioGrow1L.jpg"])
list << OpenStruct(Hash[:product_id,650,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,651,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,652,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,653,:photo_url,"http://www.hydrogarden.com/StockPics/05-225-055_BioBizz_BioBloom1L.jpg"])
list << OpenStruct(Hash[:product_id,654,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,655,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,656,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,674,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,675,:photo_url,"http://www.hydrogarden.com/StockPics/formulux_1L.JPG"])
list << OpenStruct(Hash[:product_id,676,:photo_url,"http://www.hydrogarden.com/StockPics/formulux_1L.JPG"])
list << OpenStruct(Hash[:product_id,677,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Grow1L.jpg"])
list << OpenStruct(Hash[:product_id,678,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Grow5L.jpg"])
list << OpenStruct(Hash[:product_id,680,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Grow1LHW.jpg"])
list << OpenStruct(Hash[:product_id,681,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Grow5LHW.jpg"])
list << OpenStruct(Hash[:product_id,683,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Bloom1L.jpg"])
list << OpenStruct(Hash[:product_id,684,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Bloom5L.jpg"])
list << OpenStruct(Hash[:product_id,686,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Bloom1LHW.jpg"])
list << OpenStruct(Hash[:product_id,687,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Bloom5LHW.jpg"])
list << OpenStruct(Hash[:product_id,689,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Boost1L.jpg"])
list << OpenStruct(Hash[:product_id,690,:photo_url,"http://www.hydrogarden.com/StockPics/Ionic_Boost5L.jpg"])
list << OpenStruct(Hash[:product_id,692,:photo_url,"http://www.hydrogarden.com/StockPics/wetting_agent150ml.jpg"])
list << OpenStruct(Hash[:product_id,693,:photo_url,"http://www.hydrogarden.com/StockPics/Nitrozyme_100ml.JPG"])
list << OpenStruct(Hash[:product_id,694,:photo_url,"http://www.hydrogarden.com/StockPics/Nitrozyme_250ml.jpg"])
list << OpenStruct(Hash[:product_id,695,:photo_url,"http://www.hydrogarden.com/StockPics/Nitrozyme_1L.jpg"])
list << OpenStruct(Hash[:product_id,697,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_gro1L.JPG"])
list << OpenStruct(Hash[:product_id,698,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_gro5L.JPG"])
list << OpenStruct(Hash[:product_id,699,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_gro10L.JPG"])
list << OpenStruct(Hash[:product_id,700,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_bloom1L.JPG"])
list << OpenStruct(Hash[:product_id,701,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_bloom5L.JPG"])
list << OpenStruct(Hash[:product_id,702,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_bloom10L.JPG"])
list << OpenStruct(Hash[:product_id,703,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro1L.JPG"])
list << OpenStruct(Hash[:product_id,704,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro5L.JPG"])
list << OpenStruct(Hash[:product_id,705,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro10L.JPG"])
list << OpenStruct(Hash[:product_id,706,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro1LHW.JPG"])
list << OpenStruct(Hash[:product_id,707,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro5LHW.JPG"])
list << OpenStruct(Hash[:product_id,708,:photo_url,"http://www.hydrogarden.com/StockPics/Flora_micro10LHW.JPG"])
list << OpenStruct(Hash[:product_id,709,:photo_url,"http://www.hydrogarden.com/StockPics/GH_TotalGro_1L.jpg"])
list << OpenStruct(Hash[:product_id,710,:photo_url,"http://www.hydrogarden.com/StockPics/GH_TotalGro_5L.jpg"])
list << OpenStruct(Hash[:product_id,711,:photo_url,"http://www.hydrogarden.com/StockPics/GH_TotalBloom_1L.jpg"])
list << OpenStruct(Hash[:product_id,720,:photo_url,"http://www.hydrogarden.com/StockPics/GH_DiamondNectar_500ml.JPG"])
list << OpenStruct(Hash[:product_id,721,:photo_url,"http://www.hydrogarden.com/StockPics/GH_DiamondNectar_1L.JPG"])
list << OpenStruct(Hash[:product_id,722,:photo_url,"http://www.hydrogarden.com/StockPics/GH_Ripen500ml.jpg"])
list << OpenStruct(Hash[:product_id,723,:photo_url,"http://www.hydrogarden.com/StockPics/GH_Ripen1L.jpg"])
list << OpenStruct(Hash[:product_id,724,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,725,:photo_url,"http://www.hydrogarden.com/StockPics/H2O2_250ml.jpg"])
list << OpenStruct(Hash[:product_id,730,:photo_url,"http://www.hydrogarden.com/StockPics/vaportek_optimum4000_unit.JPG"])
list << OpenStruct(Hash[:product_id,731,:photo_url,"http://www.hydrogarden.com/StockPics/vaportek_4000cartridge.JPG"])
list << OpenStruct(Hash[:product_id,732,:photo_url,"http://www.hydrogarden.com/StockPics/vaportek_4000cartridge.JPG"])
list << OpenStruct(Hash[:product_id,733,:photo_url,"http://www.hydrogarden.com/StockPics/vaportek_2speedround_unit.JPG"])
list << OpenStruct(Hash[:product_id,734,:photo_url,"http://www.hydrogarden.com/StockPics/VaportekRound_ReplacementCart.JPG"])
list << OpenStruct(Hash[:product_id,735,:photo_url,"http://www.hydrogarden.com/StockPics/Orange_mate.jpg"])
list << OpenStruct(Hash[:product_id,736,:photo_url,"http://www.hydrogarden.com/StockPics/Lemon_mate.jpg"])
list << OpenStruct(Hash[:product_id,737,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrozone.jpg"])
list << OpenStruct(Hash[:product_id,738,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrozone_Replacement_CeramicPlate.jpg"])
list << OpenStruct(Hash[:product_id,740,:photo_url,"http://www.hydrogarden.com/StockPics/Hydrozone_OzoneTestKit.jpg"])
list << OpenStruct(Hash[:product_id,761,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,763,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,769,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,770,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,771,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,772,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,774,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,785,:photo_url,"http://www.hydrogarden.com/StockPics/TDmixvent_fan.jpg"])
list << OpenStruct(Hash[:product_id,786,:photo_url,"http://www.hydrogarden.com/StockPics/TDmixvent_fan.jpg"])
list << OpenStruct(Hash[:product_id,787,:photo_url,"http://www.hydrogarden.com/StockPics/TDmixvent_fan.jpg"])
list << OpenStruct(Hash[:product_id,788,:photo_url,"http://www.hydrogarden.com/StockPics/TDmixvent_fan.jpg"])
list << OpenStruct(Hash[:product_id,801,:photo_url,"http://www.hydrogarden.com/StockPics/HydroGarden_Primair.jpg"])
list << OpenStruct(Hash[:product_id,802,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer100-125.JPG"])
list << OpenStruct(Hash[:product_id,803,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer150-125.JPG"])
list << OpenStruct(Hash[:product_id,804,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer160-150.JPG"])
list << OpenStruct(Hash[:product_id,805,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer160-125.JPG"])
list << OpenStruct(Hash[:product_id,806,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer200-125.JPG"])
list << OpenStruct(Hash[:product_id,807,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer200-160.JPG"])
list << OpenStruct(Hash[:product_id,808,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer200-250.JPG"])
list << OpenStruct(Hash[:product_id,809,:photo_url,"http://www.hydrogarden.com/StockPics/vent_reducer250-315.JPG"])
list << OpenStruct(Hash[:product_id,811,:photo_url,"http://www.hydrogarden.com/StockPics/Carbonfilter_160.JPG"])
list << OpenStruct(Hash[:product_id,812,:photo_url,"http://www.hydrogarden.com/StockPics/Carbonfilter_420.JPG"])
list << OpenStruct(Hash[:product_id,813,:photo_url,"http://www.hydrogarden.com/StockPics/Carbonfilter_760.JPG"])
list << OpenStruct(Hash[:product_id,814,:photo_url,"http://www.hydrogarden.com/StockPics/Carbonfilter_980.JPG"])
list << OpenStruct(Hash[:product_id,819,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,822,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-100_MistMaker_DK3.jpg"])
list << OpenStruct(Hash[:product_id,823,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-105_MistMaker_DK5.jpg"])
list << OpenStruct(Hash[:product_id,824,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-150-MistMaker_FloatDK3.jpg"])
list << OpenStruct(Hash[:product_id,825,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-155_MistMaker_FloatDK5.jpg"])
list << OpenStruct(Hash[:product_id,829,:photo_url,"http://www.hydrogarden.com/StockPics/PestOff_Pistol.JPG"])
list << OpenStruct(Hash[:product_id,830,:photo_url,"http://www.hydrogarden.com/StockPics/Cloth_DuctTape.jpg"])
list << OpenStruct(Hash[:product_id,832,:photo_url,"http://www.hydrogarden.com/StockPics/silicon.jpg"])
list << OpenStruct(Hash[:product_id,834,:photo_url,"http://www.hydrogarden.com/StockPics/09-410-020_Essentials_pHMeter.jpg"])
list << OpenStruct(Hash[:product_id,836,:photo_url,"http://www.hydrogarden.com/StockPics/09-420-005_pHDown25_250ml.jpg"])
list << OpenStruct(Hash[:product_id,837,:photo_url,"http://www.hydrogarden.com/StockPics/CFstandard_250ml.JPG"])
list << OpenStruct(Hash[:product_id,839,:photo_url,"http://www.hydrogarden.com/StockPics/CFstandard_1L.JPG"])
list << OpenStruct(Hash[:product_id,840,:photo_url,"http://www.hydrogarden.com/StockPics/pHBuffer4_250ml.JPG"])
list << OpenStruct(Hash[:product_id,842,:photo_url,"http://www.hydrogarden.com/StockPics/pHBuffer4_1L.JPG"])
list << OpenStruct(Hash[:product_id,843,:photo_url,"http://www.hydrogarden.com/StockPics/pHBuffer7_250ml.JPG"])
list << OpenStruct(Hash[:product_id,845,:photo_url,"http://www.hydrogarden.com/StockPics/pHBuffer7_1L.JPG"])
list << OpenStruct(Hash[:product_id,848,:photo_url,"http://www.hydrogarden.com/StockPics/Awaiting Image.jpg"])
list << OpenStruct(Hash[:product_id,849,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_Phdown_grow.jpg"])
list << OpenStruct(Hash[:product_id,850,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_Phdown_bloom.jpg"])
list << OpenStruct(Hash[:product_id,851,:photo_url,"http://www.hydrogarden.com/StockPics/Canna_Phup.JPG"])
list << OpenStruct(Hash[:product_id,852,:photo_url,"http://www.hydrogarden.com/StockPics/09-415-020_Essentials_ECMeter.jpg"])
list << OpenStruct(Hash[:product_id,857,:photo_url,"http://www.hydrogarden.com/StockPics/dial_hydrometer.jpg"])
list << OpenStruct(Hash[:product_id,858,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-050_NutrientGrowroom_Thermometer.jpg"])
list << OpenStruct(Hash[:product_id,859,:photo_url,"http://www.hydrogarden.com/StockPics/09-435-060_MinMax_ThermoHygrometer.jpg"])
list << OpenStruct(Hash[:product_id,861,:photo_url,"http://www.hydrogarden.com/StockPics/microscope_pocket.JPG"])
list << OpenStruct(Hash[:product_id,862,:photo_url,"http://www.hydrogarden.com/StockPics/microscope.JPG"])
list << OpenStruct(Hash[:product_id,865,:photo_url,"http://www.hydrogarden.com/StockPics/grasslinTimer_mechanical.jpg"])
list << OpenStruct(Hash[:product_id,866,:photo_url,"http://www.hydrogarden.com/StockPics/grasslinTimer_electrical.jpg"])
list << OpenStruct(Hash[:product_id,874,:photo_url,"http://www.hydrogarden.com/StockPics/insect_trap.jpg"])
list << OpenStruct(Hash[:product_id,876,:photo_url,"http://www.hydrogarden.com/StockPics/PestOff250ml.JPG"])
list << OpenStruct(Hash[:product_id,877,:photo_url,"http://www.hydrogarden.com/StockPics/10-475-100_Neem250ml.jpg"])
list << OpenStruct(Hash[:product_id,878,:photo_url,"http://www.hydrogarden.com/StockPics/10-475-150_GnatOff250ml.jpg"])
list << OpenStruct(Hash[:product_id,879,:photo_url,"http://www.hydrogarden.com/StockPics/10-475-200_BudRotStop_250ml.jpg"])
list << OpenStruct(Hash[:product_id,880,:photo_url,"http://www.hydrogarden.com/StockPics/Yoyo.JPG"])
list << OpenStruct(Hash[:product_id,881,:photo_url,"http://www.hydrogarden.com/StockPics/Syringe10cc.jpg"])
list << OpenStruct(Hash[:product_id,882,:photo_url,"http://www.hydrogarden.com/StockPics/Syringe100cc.jpg"])
list << OpenStruct(Hash[:product_id,883,:photo_url,"http://www.hydrogarden.com/StockPics/Pipette3.5cc.jpg"])
list << OpenStruct(Hash[:product_id,894,:photo_url,"http://www.hydrogarden.com/StockPics/Aquatherm100w_SubmersibleHeater.JPG"])
list << OpenStruct(Hash[:product_id,895,:photo_url,"http://www.hydrogarden.com/StockPics/Aquatherm200w_SubmersibleHeater.JPG"])
list << OpenStruct(Hash[:product_id,896,:photo_url,"http://www.hydrogarden.com/StockPics/Aquatherm300w_SubmersibleHeater.JPG"])
list << OpenStruct(Hash[:product_id,904,:photo_url,"http://www.hydrogarden.com/StockPics/clonex50ml.jpg"])
list << OpenStruct(Hash[:product_id,905,:photo_url,"http://www.hydrogarden.com/StockPics/Clonex250ml.jpg"])
list << OpenStruct(Hash[:product_id,906,:photo_url,"http://www.hydrogarden.com/StockPics/12-560-100_Gel4Plugs.jpg"])
list << OpenStruct(Hash[:product_id,907,:photo_url,"http://www.hydrogarden.com/StockPics/scalpels.jpg"])
list << OpenStruct(Hash[:product_id,908,:photo_url,"http://www.hydrogarden.com/StockPics/Softies_scissors.jpg"])
list << OpenStruct(Hash[:product_id,909,:photo_url,"http://www.hydrogarden.com/StockPics/Pruner_.jpg"])

list.each do |item|
    p = Photo.new :uploaded_data => item.photo_url
    p.save
    Product.find(item.product_id).photos << p
end
