#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__) + '/../config/environment')

begin
  load File.expand_path(File.dirname(__FILE__) + "/../vendor/plugins/cucumber/bin/cucumber")
rescue LoadError => e
  raise unless e.to_s =~ /cucumber/  
  require 'rubygems'
  require 'cucumber'
  load Cucumber::BINARY
end
